# Generated by Django 5.1.3 on 2025-02-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0002_biryani_curries_fastfood_quickandeasy_staters'),
    ]

    operations = [
        migrations.AddField(
            model_name='biryani',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curries',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fastfood',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickandeasy',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soups',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staters',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
