# Generated by Django 5.1.3 on 2025-01-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='juice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('ingredients', models.TextField()),
                ('recipe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='softdrinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('ingredients', models.TextField()),
                ('recipe', models.TextField()),
            ],
        ),
    ]
