# Generated by Django 5.1.3 on 2025-01-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_juice_softdrinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='softdrinks',
            new_name='smooties',
        ),
    ]
