# Generated by Django 5.1.3 on 2025-02-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_rename_softdrinks_smooties'),
    ]

    operations = [
        migrations.AddField(
            model_name='juice',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milkshakes',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mojitos',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smooties',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
