# Generated by Django 5.1.3 on 2025-02-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chocolate',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
