# Generated by Django 5.1.3 on 2025-02-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0002_chocolate_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolate',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
