# Generated by Django 5.1.3 on 2025-02-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0003_alter_chocolate_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolate',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
