# Generated by Django 5.1.3 on 2025-02-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0004_alter_chocolate_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caramel',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookies',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fruits',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
