# Generated by Django 5.1.3 on 2025-02-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosa',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idly',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poha',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puri',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upma',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
